In [1]:
import os
import sys

# Add the src directory to the Python path
notebook_dir = os.getcwd()  # Current working directory of the notebook
parent_dir = os.path.abspath(os.path.join(notebook_dir, '..'))
if parent_dir not in sys.path:
    sys.path.append(parent_dir)
from utils.factory import create_geospatial_analyzer

In [2]:
import geopandas as gpd
import pandas as pd
import shapely

In [3]:
from utils.factory import create_geospatial_analyzer

In [4]:
from utils.GeospatialAnalyzer2 import GeospatialAnalyzer2
from shapely.geometry import Polygon

ga = create_geospatial_analyzer(use_postgis=True)

In [5]:
sample_region = gpd.read_file("../data/sample_region_mudu/mudu_village.gpkg")
sample_region_geometry = sample_region.geometry.iloc[0]

In [6]:
ga.count_features_within_region(region=sample_region_geometry, layer_or_table="public.lamwo_buildings")

268

In [7]:
ga.region_total_biomass(region=sample_region_geometry)

66627.03865642505

In [19]:
import folium

# Get centroid of the region to center the map
centroid = sample_region_geometry.centroid
m = folium.Map(location=[centroid.y, centroid.x], zoom_start=13)

# Add the region geometry to the map
folium.GeoJson(sample_region_geometry).add_to(m)

m

In [8]:
analyzer = create_geospatial_analyzer()

AttributeError: 'int' object has no attribute 'lower'

In [10]:
analyzer.count_features_within_region(sample_region_geometry, 'buildings')

268

In [11]:
analyzer.count_features_within_region(sample_region_geometry, 'tiles')

35

In [13]:
analyzer.region_total_biomass(sample_region_geometry)

Reprojecting GeoDataFrame from EPSG:4326 to EPSG:32636 for calculation.

66627.03732742427

In [8]:
ga._analyze_environmental_metrics(sample_region_geometry)

{'ndvi_mean': -0.5122,
 'ndvi_med': -0.5806,
 'ndvi_std': 0.2273,
 'evi_med': 1.4574,
 'elev_mean': 849.5706,
 'slope_mean': 2.5659,
 'par_mean': 179.2317,
 'rain_total_mm': 34.5617,
 'rain_mean_mm_day': 3.2298,
 'cloud_free_days': 29.0,
 'vegetation_density': 'Very limited vegetation',
 'total_biomass_Mg': 66627.0387,
 'region_area_km2': 20.6963}

In [10]:
ga.get_villages_info_within_region(sample_region_geometry)

,ogc_fid,geom,id,addr_vname,rank,category
0,88,"POLYGON ((32.45556 3.52822, 32.45652 3.52907, ...",5502886,Otaa,NaN,Solar home system
1,89,"POLYGON ((32.42204 3.50881, 32.42188 3.50937, ...",5502887,Mudu Central,NaN,Existing minigrid
2,90,"POLYGON ((32.48048 3.46875, 32.48159 3.47877, ...",5502888,Mudu East,21.0,Candidate minigrid
3,100,"POLYGON ((32.46802 3.43551, 32.46857 3.43699, ...",5502898,Padwat Central,12.0,Candidate minigrid
4,102,"POLYGON ((32.48745 3.45855, 32.48802 3.45829, ...",5502900,Padwat East,32.0,Candidate minigrid
5,108,"POLYGON ((32.49077 3.42482, 32.49875 3.43083, ...",5502906,Lugwar Central,4.0,Candidate minigrid
6,111,"POLYGON ((32.51499 3.46484, 32.51508 3.46617, ...",5502909,Lanywang West,15.0,Candidate minigrid
7,113,"POLYGON ((32.47974 3.52567, 32.48022 3.52603, ...",5502911,Lanywang Central,NaN,Solar home system

In [14]:
analyzer._analyze_environmental_metrics(sample_region_geometry)

Reprojecting GeoDataFrame from EPSG:4326 to EPSG:32636 for calculation.
Reprojecting GeoDataFrame from EPSG:4326 to EPSG:32636 for calculation.

{'ndvi_mean': -0.5122,
 'ndvi_med': -0.5806,
 'ndvi_std': 0.2273,
 'evi_med': 1.4574,
 'elev_mean': 849.5706,
 'slope_mean': 2.5659,
 'par_mean': 179.2317,
 'rain_total_mm': 34.5617,
 'rain_mean_mm_day': 3.2298,
 'cloud_free_days': 29.0,
 'region_area_km2': 20.6963,
 'vegetation_density': 'Very limited vegetation',
 'total_biomass_Mg': 66627.03732742427}

In [10]:
analyzer.avg_ndvi(sample_region_geometry)

Reprojecting GeoDataFrame from EPSG:4326 to EPSG:32636 for calculation.

-0.5121903091796086

In [16]:
analyzer.get_minigrids_info_within_region(sample_region.geometry.iloc[0])

AttributeError: 'GeospatialAnalyzer' object has no attribute 'get_minigrids_info_within_region'

In [17]:
analyzer.get_tiles_info_within_region(sample_region.geometry.iloc[0])['ndvi_mean'].mean()

-0.514233812830664

In [11]:
existing_minigrids = gpd.read_file("../data/viz_geojsons/existing_minigrids.geojson")

In [13]:
existing_minigrids.sort_values('Capacity', ascending=False, inplace=True)

In [14]:
existing_minigrids

,id,Location,Name,Capacity,geometry
0,16,Agoro_Incl Tumanum B,Agoro,0.08,POINT (33.01636 3.79883)
17,35,Paloga Central,Paloga Central,0.08,POINT (32.94280 3.58834)
24,56,Palabek,Base Camp TC,0.08,POINT (32.45319 3.35247)
23,55,Palabek,Palabek,0.08,POINT (32.41668 3.36141)
14,32,Ogili TC,Ogili TC,0.08,POINT (32.49622 3.40938)
5,22,Kapeta,Kapeta,0.04,POINT (32.59161 3.50416)
15,33,Opoki,Opoki,0.04,POINT (32.71950 3.42934)
26,58,Labayango,Labayango,0.04,POINT (32.86622 3.52132)
2,18,Apyeta West/Apyeta Primary School,Apyeta West,0.04,POINT (32.36870 3.30583)
22,40,Ywaya,Ywaya,0.04,POINT (33.08095 3.69453)
21,39,Potika,Potika,0.04,POINT (32.88081 3.71998)
19,37,Pany Buk East-West,Pany Buk East-West,0.04,POINT (32.94961 3.67544)
18,36,Pangira -Licwar Central,Pangira-Licwar Central,0.04,POINT (32.65234 3.61458)
4,21,Ayuu Alali,Ayuu Alali,0.04,POINT (32.55980 3.53905)
6,24,Lapidiyenyi,Lapidiyenyi,0.04,POINT (32.92919 3.58105)
16,34,Otaa,Otaa,0.04,POINT (32.47962 3.48625)
1,17,Apwoyo TC,Apwoyo TC,0.04,POINT (32.99998 3.75932)
13,31,Oboko TC,Oboko TC,0.04,POINT (32.98424 3.67091)
12,30,Ngomoromo,Ngomoromo,0.04,POINT (32.58623 3.68851)
11,29,Muddu Central,Muddu Central,0.04,POINT (32.45229 3.49704)
9,27,Loromibeng A-B,Loromibeng A-B,0.04,POINT (33.04055 3.75589)
8,26,Logwak,Logwak,0.04,POINT (32.74118 3.66006)
27,59,Apyetta TC,Apyetta TC,0.04,POINT (32.41602 3.37312)
20,38,Pawena TC,Pawena TC,0.02,POINT (32.66910 3.28127)
10,28,Moroto East,Moroto East,0.02,POINT (32.92925 3.69297)
3,20,Aweno Olwi,Aweno Olwi,0.02,POINT (32.74772 3.71898)
25,57,Labayango,Labayango Primary School,0.02,POINT (32.86379 3.52098)
7,25,Lelapwot West,Lelapwot West,0.02,POINT (32.70874 3.62690)